name: apache-proxy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy to Docker Hub
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: echo "APACHE_OIDC_REPO=somrit/apache-oidc" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_API_TOKEN: ${{ secrets.DOCKER_API_TOKEN }}
      run: echo "${{ secrets.DOCKER_API_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -f apache-oidc/Dockerfile -t ${{ env.APACHE_OIDC_REPO }}:github-build-${{ github.run_number }} -t ${{ env.APACHE_OIDC_REPO }}:latest .

    - name: Push Docker image
      run: |
        docker push ${{ env.APACHE_OIDC_REPO }}:github-build-${{ github.run_number }}
        docker push ${{ env.APACHE_OIDC_REPO }}:latest
